import Image from "next/image";
import { calculateDocumentTotals, calculateLine, formatAdminDate, formatMoney } from "./money";
import type { BillingDocument, Payment } from "../types";

export function InvoiceDocument({ document, payments }: { document: BillingDocument; payments: Payment[] }) {
  const totals = calculateDocumentTotals(document, payments);
  const label = document.type === "standard" ? "Invoice" : document.type === "proforma" ? "Proforma invoice" : "Recurring invoice";
  return (
    <article className="mx-auto flex aspect-[1/1.414] w-full max-w-[860px] flex-col overflow-hidden bg-white text-slate-900 shadow-[0_16px_55px_rgba(15,23,42,0.13)] ring-1 ring-slate-200 print:shadow-none print:ring-0">
      <div className="h-2 shrink-0 bg-ktf-blue" />
      <div className="flex flex-1 flex-col px-[7.4%] pb-[7.4%] pt-[5.5%]">
        <header className="flex -translate-y-2 items-start justify-between gap-8">
          <Image src="/brand/bespoke-technologies-logo.png" alt="Bespoke Technologies" width={340} height={112} className="h-auto w-[45%] -translate-y-4 object-contain object-left" priority />
          <div className="text-right"><p className="text-[clamp(8px,1.15vw,15px)] font-bold uppercase tracking-[0.08em] text-ktf-blue">{document.type === "proforma" ? "For approval" : "Billing document"}</p><h2 className="mt-2 text-[clamp(24px,4vw,50px)] font-extrabold leading-none tracking-[-0.04em]">{label}</h2><p className="mt-5 text-[clamp(9px,1.3vw,17px)] font-bold">{document.documentNumber}</p><p className="mt-2 text-[clamp(8px,1.1vw,15px)] text-slate-500">Issued {formatAdminDate(document.issueDate)}</p><p className="text-[clamp(8px,1.1vw,15px)] text-slate-500">Due {formatAdminDate(document.dueDate)}</p></div>
        </header>
        <section className="mt-[4%] grid grid-cols-2 gap-10 border-t border-slate-200 pt-[3.5%]"><div><p className="text-[clamp(8px,1vw,13px)] font-bold uppercase tracking-[0.12em] text-slate-500">From</p><h3 className="mt-3 text-[clamp(12px,2vw,25px)] font-bold">{document.company.name}</h3><p className="mt-2 text-[clamp(8px,1.15vw,15px)] leading-relaxed text-slate-500">{document.company.email}<br />{document.company.phone} · {document.company.website}<br />Business Name Registration Number {document.company.registrationNumber}</p></div><div><p className="text-[clamp(8px,1vw,13px)] font-bold uppercase tracking-[0.12em] text-slate-500">Bill to</p><h3 className="mt-3 text-[clamp(12px,2vw,25px)] font-bold">{document.client.name}</h3><p className="mt-2 text-[clamp(8px,1.15vw,15px)] leading-relaxed text-slate-500">{document.client.contactName}<br />{document.client.email}<br />{document.client.phone}<br />{document.client.address}</p></div></section>
        <section className="mt-[2.5%]"><div className="grid grid-cols-[1fr_9%_18%_20%] border-y border-blue-200 bg-blue-50 px-[2%] py-[2.2%] text-[clamp(7px,0.9vw,12px)] font-bold uppercase tracking-[0.08em] text-blue-700"><span>Service description</span><span>Qty</span><span className="text-right">Rate</span><span className="text-right">Amount</span></div>{document.items.map((item) => <div key={item.id} className="grid grid-cols-[1fr_9%_18%_20%] border-b border-slate-100 px-[2%] py-[2.7%] text-[clamp(8px,1.1vw,14px)]"><span><strong className="block text-[clamp(9px,1.3vw,17px)]">{item.name}</strong>{item.description && <span className="mt-1 block text-[clamp(7px,1vw,13px)] leading-relaxed text-slate-500">{item.description}</span>}</span><span>{item.quantity}</span><span className="text-right text-slate-600">{formatMoney(item.rate, document.currency)}</span><span className="text-right font-bold">{formatMoney(calculateLine(item).total, document.currency)}</span></div>)}</section>
        <section className="mt-[3%] grid grid-cols-2 gap-10"><div className="space-y-3 text-[clamp(7px,1vw,13px)] leading-relaxed text-slate-500">{document.paymentInstructions && <div><p className="font-bold uppercase tracking-wide text-slate-600">Payment instructions</p><p className="mt-1 whitespace-pre-line">{document.paymentInstructions}</p></div>}{document.notes && <div><p className="font-bold uppercase tracking-wide text-slate-600">Notes</p><p className="mt-1">{document.notes}</p></div>}{document.terms && <div><p className="font-bold uppercase tracking-wide text-slate-600">Terms</p><p className="mt-1">{document.terms}</p></div>}</div><div className="text-[clamp(8px,1.1vw,14px)]"><div className="flex justify-between py-2 text-slate-500"><span>Subtotal</span><span>{formatMoney(totals.subtotal, document.currency)}</span></div>{totals.discount > 0 && <div className="flex justify-between py-1.5 text-slate-500"><span>Discount</span><span>-{formatMoney(totals.discount, document.currency)}</span></div>}{totals.tax > 0 && <div className="flex justify-between py-1.5 text-slate-500"><span>Tax</span><span>{formatMoney(totals.tax, document.currency)}</span></div>}{totals.paid > 0 && <div className="flex justify-between py-1.5 text-emerald-700"><span>Paid</span><span>{formatMoney(totals.paid, document.currency)}</span></div>}<div className="mt-2 flex items-center justify-between bg-ktf-blue p-[7%] text-white"><span className="text-[clamp(7px,0.9vw,12px)] font-bold uppercase">{document.type === "proforma" ? "Proposed total" : "Balance due"}</span><span className="text-[clamp(13px,2.2vw,28px)] font-extrabold">{formatMoney(totals.balance, document.currency)}</span></div></div></section>
        <footer className="mt-auto flex items-center justify-between border-t border-blue-200 pt-[2%] text-[clamp(6px,0.9vw,11px)] font-bold uppercase tracking-wide text-slate-500"><span>{document.company.motto}</span><span>Page 1</span></footer>
      </div>
    </article>
  );
}
