import Link from "next/link";
import { notFound } from "next/navigation";
import { Download, Pencil, RefreshCw, Send, ShieldAlert, WalletCards } from "lucide-react";
import { requireAdminPermission } from "@/features/admin/access";
import { calculateDocumentTotals, formatAdminDate, formatMoney } from "@/features/admin/billing/money";
import { InvoiceDocument } from "@/features/admin/billing/invoice-document";
import { inputClass, labelClass, Panel, PanelHeader, primaryButtonClass, secondaryButtonClass, StatusPill, textareaClass } from "@/features/admin/components/admin-ui";
import { getAdminSnapshot } from "@/features/admin/repository";
import { convertProformaAction, createBillingRevisionAction, recordPaymentAction, requestBillingApprovalAction, reversePaymentAction, transitionBillingAction, updateRecurringStateAction } from "../../actions";

export default async function BillingDocumentPage({ params }: { params: Promise<{ id: string }> }) {
  const session = await requireAdminPermission("billing.manage");
  const id = (await params).id;
  const snapshot = await getAdminSnapshot();
  const document = snapshot.documents.find((candidate) => candidate.id === id);
  if (!document) notFound();
  const payments = snapshot.payments.filter((payment) => payment.documentId === document.id);
  const totals = calculateDocumentTotals(document, snapshot.payments);
  const needsFounderApproval = session.role === "admin_manager" && totals.total > snapshot.settings.invoiceApprovalThreshold;
  const project = snapshot.projects.find((candidate) => candidate.id === document.projectId);
  const history = snapshot.billingEvents.filter((event) => event.documentId === document.id);
  const runs = snapshot.recurringRuns.filter((run) => run.templateDocumentId === document.id);

  return (
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_340px]">
      <InvoiceDocument document={document} payments={snapshot.payments} />
      <aside className="space-y-5 xl:sticky xl:top-28 xl:self-start">
        <Panel><PanelHeader title={document.documentNumber} description={`${document.type.replaceAll("_", " ")} · revision ${document.revision}`} action={<StatusPill value={document.recurrence?.state ?? document.status} />} /><div className="space-y-4 p-5"><dl className="grid grid-cols-2 gap-4 text-xs"><div><dt className="text-slate-400">Client</dt><dd className="mt-1 font-semibold text-slate-800">{document.client.name}</dd></div><div><dt className="text-slate-400">Due</dt><dd className="mt-1 font-semibold text-slate-800">{formatAdminDate(document.dueDate)}</dd></div><div><dt className="text-slate-400">Total</dt><dd className="mt-1 font-semibold text-slate-800">{formatMoney(totals.total, document.currency)}</dd></div><div><dt className="text-slate-400">Balance</dt><dd className="mt-1 font-semibold text-slate-800">{formatMoney(totals.balance, document.currency)}</dd></div></dl>{project && <Link href="/admin/projects" className="block rounded-lg bg-blue-50 px-3 py-2 text-xs font-semibold text-blue-700">Linked project: {project.name}</Link>}<Link href={`/admin/api/billing/${document.id}/pdf`} className={`${secondaryButtonClass} w-full`}><Download className="h-4 w-4" /> Download PDF</Link>
          {document.status === "draft" && <Link href={`/admin/billing/${document.id}/edit`} className={`${secondaryButtonClass} w-full`}><Pencil className="h-4 w-4" /> Edit draft</Link>}
          {document.status === "draft" && (needsFounderApproval ? <form action={requestBillingApprovalAction} className="space-y-2"><input type="hidden" name="id" value={document.id} /><label><span className={labelClass}>Approval reason</span><textarea className={textareaClass} name="reason" defaultValue={`Document total exceeds the ${formatMoney(snapshot.settings.invoiceApprovalThreshold)} manager threshold.`} required /></label><button className={`${primaryButtonClass} w-full`}><ShieldAlert className="h-4 w-4" /> Request founder approval</button></form> : <form action={transitionBillingAction}><input type="hidden" name="id" value={document.id} /><input type="hidden" name="status" value="approved" /><input type="hidden" name="reason" value="Approved through the admin billing workflow." /><button className={`${primaryButtonClass} w-full`}><ShieldAlert className="h-4 w-4" /> Approve document</button></form>)}
          {document.status === "approved" && document.type !== "recurring" && <form action={transitionBillingAction} className="space-y-3"><input type="hidden" name="id" value={document.id} /><input type="hidden" name="status" value="sent" /><input type="hidden" name="reason" value="Manual delivery confirmed by the admin." /><label className="flex items-start gap-2 text-xs leading-5 text-slate-600"><input className="mt-1" type="checkbox" name="confirmed" value="yes" required /> I confirm this document was actually delivered to the client.</label><button className={`${primaryButtonClass} w-full`}><Send className="h-4 w-4" /> Confirm manually sent</button></form>}
          {document.type === "proforma" && ["sent", "viewed", "accepted", "approved"].includes(document.status) && <form action={convertProformaAction}><input type="hidden" name="id" value={document.id} /><button className={`${secondaryButtonClass} w-full`}>Convert to standard invoice</button></form>}
          {document.type !== "recurring" && document.status !== "draft" && <form action={createBillingRevisionAction}><input type="hidden" name="id" value={document.id} /><button className={`${secondaryButtonClass} w-full`}><RefreshCw className="h-4 w-4" /> Create revised draft</button></form>}
          {document.recurrence && document.recurrence.state !== "ended" && <details><summary className="cursor-pointer text-xs font-semibold text-slate-600">Manage recurring schedule</summary><form action={updateRecurringStateAction} className="mt-3 space-y-2"><input type="hidden" name="id" value={document.id} /><label><span className={labelClass}>Next state</span><select className={inputClass} name="state" defaultValue={document.recurrence.state === "active" ? "paused" : "active"}><option value="active">Active / retry</option><option value="paused">Paused</option><option value="ended">Ended</option></select></label><label><span className={labelClass}>Reason</span><input className={inputClass} name="reason" required /></label><button className={`${secondaryButtonClass} w-full`}>Update schedule</button></form></details>}
          {session.role === "founder_admin" && !["voided"].includes(document.status) && <details><summary className="cursor-pointer text-xs font-semibold text-rose-700">Void this document</summary><form action={transitionBillingAction} className="mt-3 space-y-2"><input type="hidden" name="id" value={document.id} /><input type="hidden" name="status" value="voided" /><label><span className={labelClass}>Reason</span><textarea className={textareaClass} name="reason" required /></label><button className="inline-flex h-9 items-center rounded-lg bg-rose-700 px-3 text-xs font-semibold text-white">Confirm void</button></form></details>}
        </div></Panel>

        {document.type === "standard" && ["sent", "viewed", "partially_paid", "overdue"].includes(document.status) && totals.balance > 0 && <Panel><PanelHeader title="Record payment" description="Balances are derived from payment allocations." action={<WalletCards className="h-4 w-4 text-emerald-700" />} /><form action={recordPaymentAction} className="space-y-3 p-5"><input type="hidden" name="documentId" value={document.id} /><label><span className={labelClass}>Amount ({document.currency})</span><input className={inputClass} name="amount" type="number" min="0.01" max={totals.balance} step="0.01" defaultValue={totals.balance} required /></label><label><span className={labelClass}>Paid at</span><input className={inputClass} name="paidAt" type="datetime-local" required /></label><label><span className={labelClass}>Method</span><select className={inputClass} name="method" defaultValue="Bank transfer"><option>Bank transfer</option><option>Cash</option><option>Card</option><option>Other</option></select></label><label><span className={labelClass}>Reference</span><input className={inputClass} name="reference" required /></label><label><span className={labelClass}>Note</span><textarea className={textareaClass} name="note" /></label><button className={`${primaryButtonClass} w-full`}>Record confirmed payment</button></form></Panel>}

        {payments.length > 0 && <Panel><PanelHeader title="Payment history" description="Every change remains attributable." /><div className="divide-y divide-slate-100">{payments.map((payment) => <article key={payment.id} className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold text-slate-900">{formatMoney(payment.amount, payment.currency)}</p><p className="mt-1 text-[11px] text-slate-500">{formatAdminDate(payment.paidAt)} · {payment.reference}</p></div><StatusPill value={payment.state} /></div>{session.role === "founder_admin" && payment.state === "recorded" && <details className="mt-3"><summary className="cursor-pointer text-[11px] font-semibold text-rose-700">Reverse payment</summary><form action={reversePaymentAction} className="mt-2 space-y-2"><input type="hidden" name="id" value={payment.id} /><input type="hidden" name="documentId" value={document.id} /><textarea name="reason" className={textareaClass} placeholder="Required reversal reason" required /><button className="h-8 rounded-lg bg-rose-700 px-3 text-[11px] font-semibold text-white">Reverse with audit</button></form></details>}</article>)}</div></Panel>}

        {(history.length > 0 || runs.length > 0) && <Panel><PanelHeader title={document.type === "recurring" ? "Schedule and document history" : "Document history"} description="Append-only lifecycle evidence." /><div className="divide-y divide-slate-100">{runs.map((run) => <article key={run.id} className="p-4"><div className="flex items-center justify-between gap-2"><p className="text-xs font-semibold text-slate-700">Recurring run · {formatAdminDate(run.dueDate)}</p><StatusPill value={run.state} /></div>{run.error && <p className="mt-2 text-[11px] text-rose-700">{run.error}</p>}</article>)}{history.map((event) => <article key={event.id} className="p-4"><p className="text-xs font-semibold text-slate-700">{event.type.replaceAll("_", " ")}</p><p className="mt-1 text-[11px] text-slate-400">{formatAdminDate(event.createdAt)}{event.fromStatus || event.toStatus ? ` · ${event.fromStatus ?? "start"} → ${event.toStatus ?? ""}` : ""}</p></article>)}</div></Panel>}
      </aside>
    </div>
  );
}
